package com.amoy.zhp.splearning.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.QUESTION_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.COMMENTOR_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Long commentorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.CONTENT
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.LIKE_COUNT
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.GMT_MODIFIED
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.GMT_CREATED
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Long gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.COMMENT_TO_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Long commentToId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.TYPE
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.ID
     *
     * @return the value of COMMENT.ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.ID
     *
     * @param id the value for COMMENT.ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.QUESTION_ID
     *
     * @return the value of COMMENT.QUESTION_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.QUESTION_ID
     *
     * @param questionId the value for COMMENT.QUESTION_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.COMMENTOR_ID
     *
     * @return the value of COMMENT.COMMENTOR_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Long getCommentorId() {
        return commentorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.COMMENTOR_ID
     *
     * @param commentorId the value for COMMENT.COMMENTOR_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setCommentorId(Long commentorId) {
        this.commentorId = commentorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.CONTENT
     *
     * @return the value of COMMENT.CONTENT
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.CONTENT
     *
     * @param content the value for COMMENT.CONTENT
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.LIKE_COUNT
     *
     * @return the value of COMMENT.LIKE_COUNT
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.LIKE_COUNT
     *
     * @param likeCount the value for COMMENT.LIKE_COUNT
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.GMT_MODIFIED
     *
     * @return the value of COMMENT.GMT_MODIFIED
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.GMT_MODIFIED
     *
     * @param gmtModified the value for COMMENT.GMT_MODIFIED
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.GMT_CREATED
     *
     * @return the value of COMMENT.GMT_CREATED
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.GMT_CREATED
     *
     * @param gmtCreated the value for COMMENT.GMT_CREATED
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.COMMENT_TO_ID
     *
     * @return the value of COMMENT.COMMENT_TO_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Long getCommentToId() {
        return commentToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.COMMENT_TO_ID
     *
     * @param commentToId the value for COMMENT.COMMENT_TO_ID
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setCommentToId(Long commentToId) {
        this.commentToId = commentToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.TYPE
     *
     * @return the value of COMMENT.TYPE
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.TYPE
     *
     * @param type the value for COMMENT.TYPE
     *
     * @mbg.generated Tue Feb 04 09:48:56 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}